import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from '@components/Sidebar'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import {IBM_Plex_Mono} from "next/font/google";
const ibmPlexMono = IBM_Plex_Mono({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
    variable: "--font-ibm-plex-mono", });


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ESP32 LOG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`h-screen flex flex-row w-full overflow-hidden ${ibmPlexMono.variable}`}>
      <div className="sm:1/4 lg:w-2/12 h-fill">
        <Sidebar/>
      </div>
      <div className="min-h-full lg:w-10/12 sm:3/4 overflow-y-auto scroll-smooth">
      {children}
      </div>
      </body>
    </html>
  );
}
