import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import {Inconsolata} from 'next/font/google';
const inconsolata = Inconsolata({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "ESP32 LOG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", inconsolata.className)}
    >
        <body>
            {children}
        </body>
    </html>
  )
};
